### PR TITLE
Add skipped tests to report

### PR DESCRIPTION
**Pull request by nprizal**
### Description

When a test is skipped in the Test Engine using Test State Management, it’s excluded from the test plan and won’t be passed to the runner. To inform the user that a test has been skipped, we need to display it in the report. However, it’s possible for a test to be skipped by the test runner, for example, using `xit` in RSpec. Therefore, it’s important to clearly indicate whether the test was skipped by the test runner or by the Test Engine.

This Pull Request introduces a new `TestStatus` called `TestStatusSkipped` to indicate tests that were skipped by the runner. These tests will be printed alongside the skipped tests from the test plan (i.e., tests that were skipped by Test Engine) at the end of the run.

Sample report:
```
+++ ========== Buildkite Test Engine Report  ==========
✅ All tests passed.

+---------+-----------+---+
| Passed  | first run | 3 |
+         +-----------+---+
|         | on retry  | 0 |
+---------+-----------+---+
| Muted   | passed    | 1 |
+         +-----------+---+
|         | failed    | 1 |
+---------+-----------+---+
| Failed  |           | 0 |
+---------+-----------+---+
| Skipped |           | 1 |
+---------+-----------+---+
|               TOTAL | 6 |
+---------+-----------+---+

+++ Muted Tests:
- Tomato is vegetable (failed)
- Apple is red (passed)

+++ Skipped by RSpec:
- Banana is yellow

+++ Skipped by Test Engine:
- Banana is green
===================================================
```

### Context
https://linear.app/buildkite/issue/TET-448

### CODE REVIEW

**Review by niceking — COMMENTED** [review]
Looks good, could you include a screenshot of the report with the skipped?

**Comment by nprizal** [comment]
> Looks good, could you include a screenshot of the report with the skipped?

I have added the sample report in PR description.

**Comment by wooly** [comment]
I'm not sure that we should count tests skipped by Test Engine in the total tests, since these will be the same for all nodes.

**Comment by niceking** [comment]
@wooly oh yeah, that's a good point. Hmmmm. Perhaps we leave off the report, and then separate out the framework skip and the bktec skip in the details? Something like:

```
+++ ========== Buildkite Test Engine Report  ==========
✅ All tests passed.

+---------+----------------+---+
| Passed  | first run      | 4 |
+         +----------------+---+
|         | on retry       | 0 |
+---------+----------------+---+
| Muted   | passed         | 1 |
+         +----------------+---+
|         | failed         | 1 |
+---------+----------------+---+
| Failed  |                | 0 |
+---------+----------------+---+
| Skipped |             | 0 |
+         +----------------+---+
|                    TOTAL | 7 |
+---------+----------------+---+

+++ Muted Tests:
- Apple is red (passed)
- Tomato is vegetable (failed)

+++ Skipped by Rspec :
- Banana is green 

+++ Skipped by Test Engine :
- Banana is green 
===================================================
```

**Comment by nprizal** [comment]
I have excluded tests skipped by Test Engine from the table/total, and print it as separate section in the detail as @niceking suggested.

**Review by niceking — APPROVED** [review]

**Pull request merged**
